export const MissingCoinId = "Missing coinId"
export const MissingChainId= "Missing chainId"
export const UnsupportedChainId = "Unsupported chainId"
export const MissingAddress = "Missing address"
export const MissingExtendedKey = "Missing extended public key"
export const InternalTransactionsSupported ="Internal transactions not supported"