export type InternalTransactionEncode = {
    blockNumber: string;
    timeStamp?: string;
    hash?: string;
    txid?:string;
    time:string;
    transactionHash?:string;
    from: string;
    to: string;
    value: string;
    index?:string;
    contractAddress: string;
    input: string;
    type: string;
    gas: string;
    gasUsed: string;
    traceId?: string;
    isError: string;
    errCode: string;
};
